# Generated by Django 5.2.1 on 2025-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
    ]
