# Generated by Django 5.2.1 on 2025-06-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_dept_remove_project_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
    ]
